# Generated by Django 5.0.6 on 2024-06-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('city', models.CharField(choices=[('Mumbai', 'Mumbai'), ('Pune', 'Pune'), ('Jaipur', 'Jaipur'), ('Hyderabad', 'Hyderabad')], max_length=50)),
                ('query', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
