# Generated by Django 5.0.6 on 2024-06-14 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='query',
            new_name='comment',
        ),
    ]
